name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUELDONETORD }}'
          projectId: sueldonetord
          channelId: live
